---
- hosts: vb
  
  vars:
    symfony_root_dir: /var/www/html/knp_authentication
    symfony_web_dir: "{{ symfony_root_dir }}/web"
    ansible_user: vagrant
    ansible_group: vagrant

  roles:
    - java
    - php
    - apache
    - mysql

  tasks:

    - ping: ~
    
    - name: Update apt repository cache
      become: true
      apt:
          update_cache: true

    - name: Upgade existing packages
      become: true
      apt:
          upgrade: dist

    - name: Installing Cowsay
      become: true
      apt:
          name: cowsay

    - name: Install low level utilities
      become: true
      apt:
        name: "{{ item }}"
      with_items:
          - zip
          - unzip
          - tree

    - name: Install Git
      become: true
      apt:
          name: git
          state: latest

    - name: Creating Project Directory
      become: true
      file:
          path: "{{ symfony_root_dir }}"
          state: directory
          owner: "{{ ansible_user }}"
          group: "{{ ansible_user }}"
          recurse: true

    - name: Copying local SSH key to guest
      become: true
      copy:
        src: /home/wdiaz/.ssh/id_rsa
        dest: /home/vagrant/.ssh/id_rsa
        owner: vagrant
        group: vagrant
        mode: 0600
      tags:
        - ssh

    - name: Cloning Repository from Github
      become: true
      git:
        repo: git@github.com:wdiaz/SymfonyAuthentication.git
        version: master
        dest: "{{ symfony_root_dir }}"
        key_file: /home/vagrant/.ssh/id_rsa
        accept_hostkey: true
        force: true
      tags:
        - repo

    - name: Change symfony Symfony Root directory permissions
      become: true
      file:
        path: "{{ symfony_root_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: 0750
        recurse: true
      tags:
        - repo

    - name: Download Composer
      become: true
      script: scripts/download_composer.sh

    - name: Move Composer Globally
      become: true
      command: "mv composer.phar /usr/local/bin/composer"

    - name: Set permissions on composer
      become: true
      file:
        path: /usr/local/bin/composer
        mode: "a+x"

    - name: Install Composer Dependencies
      become: true
      composer: 
        working_dir: "{{ symfony_root_dir }}"
        no_dev: no
      tags:
          - deploy

  handlers:
      - name: Restart Apache2
        become: true
        service:
          name: apache2
          state: reloaded