---
- hosts: vb
  
  vars:
    symfony_root_dir: /var/www/html/knp_authentication
    symfony_web_dir: "{{ symfony_root_dir }}/web"
    home_root: "/var/www/html"
    ansible_user: vagrant
    ansible_group: vagrant

  roles:
    - php
    - apache
    - mysql

  tasks:

    - ping: ~
    
    - name: Update apt repository cache
      become: true
      apt:
          update_cache: true

    - name: Upgade existing packages
      become: true
      apt:
          upgrade: dist

    - name: Installing Cowsay
      become: true
      apt:
          name: cowsay

    - name: Install low level utilities
      become: true
      apt:
        name: "{{ item }}"
      with_items:
          - zip
          - unzip
          - tree

    - name: Install Git
      become: true
      apt:
          name: git
          state: latest

    - name: Creating Project Directory
      become: true
      file:
          path: "{{ symfony_root_dir }}"
          state: directory
          owner: "{{ ansible_user }}"
          group: "{{ ansible_user }}"
          recurse: true

    - name: Copying local private SSH key to guest
      become: true
      copy:
        src: /Users/wdiaz/.ssh/id_rsa
        dest: /home/vagrant/.ssh/id_rsa
        owner: vagrant
        group: vagrant
        mode: 0600
      tags:
        - ssh

    - name: Copying local public SSH key to guest
      become: true
      copy:
        src: /Users/wdiaz/.ssh/id_rsa.pub
        dest: /home/vagrant/.ssh/id_rsa.pub
        owner: vagrant
        group: vagrant
        mode: 0644
      tags:
        - ssh

    - name: Download Composer
      become: true
      script: scripts/download_composer.sh

    - name: Move Composer Globally
      become: true
      command: "mv composer.phar /usr/local/bin/composer"

    - name: Set permissions on composer
      become: true
      file:
        path: /usr/local/bin/composer
        mode: "a+x"


  handlers:
      - name: Restart Apache2
        become: true
        service:
          name: apache2
          state: reloaded
