---
- hosts: vb
  tasks:

    - ping: ~
    
    - name: Update apt repository cache
      become: true
      apt:
          update_cache: true

    - name: Upgade existing packages
      become: true
      apt:
          upgrade: dist

    - name: Installing Cowsay
      become: true
      apt:
          name: cowsay

    - name: Install Git
      become: true
      apt:
          name: git
          state: latest
    
    - name: Install PHP PPA Repository
      become: true
      apt_repository:
          repo: 'ppa:ondrej/php'

    - name: Install MySQL Server
      become: true
      apt:
          name: mysql-server
          state: latest

    - name: Install Apache
      become: true
      apt:
          name: apache2

    - name: Install PHP 7.2 and its Modules
      become: true
      apt:
          name: "{{ item }}"
          state: latest
      with_items:
          - php7.2-cli
          - php7.2-mysql
          - php7.2-curl
          - php7.2-intl
          - php7.2-ldap
          - php7.2-gd
          - php7.2-opcache
          - php7.2-common
          - php7.2-xml
          - php7.2-xmlrpc
          - php7.2-bcmath
          - php7.2-bz2
          - php7.2-mbstring
          - php7.2-soap
          - php7.2-xsl
          - php7.2-zip