---
- name: Install PHP 7.2 and its Modules
  become: true
  apt:
      name: "{{ item }}"
      state: latest
  with_items:
      - php7.2-cli
      - php7.2-mysql
      - php7.2-curl
      - php7.2-intl
      - php7.2-ldap
      - php7.2-gd
      - php7.2-opcache
      - php7.2-common
      - php7.2-xml
      - php7.2-xmlrpc
      - php7.2-bcmath
      - php7.2-bz2
      - php7.2-mbstring
      - php7.2-soap
      - php7.2-xsl
      - php7.2-zip
      - libapache2-mod-php7.2

- name: Install PHP PPA Repository
  become: true
  apt_repository:
      repo: 'ppa:ondrej/php'

- name: Replacing PHP timezone
  become: true
  lineinfile:
      dest: /etc/php/7.2/cli/php.ini
      regexp: "date.timezone ="
      line: "date.timezone = UTC"