---
- name: Install PHP PPA Repository
  become: true
  apt_repository:
      repo: 'ppa:ondrej/php'

- name: Install PHP 7.3 and its Modules
  become: true
  apt:
      name: "{{ item }}"
      state: latest
  with_items:
      - php7.3-cli
      - php7.3-mysql
      - php7.3-curl
      - php7.3-intl
      - php7.3-ldap
      - php7.3-gd
      - php7.3-opcache
      - php7.3-common
      - php7.3-xml
      - php7.3-xmlrpc
      - php7.3-bcmath
      - php7.3-bz2
      - php7.3-mbstring
      - php7.3-soap
      - php7.3-xsl
      - php7.3-zip
      - libapache2-mod-php7.3

- name: Replacing PHP timezone
  become: true
  lineinfile:
      dest: /etc/php/7.3/cli/php.ini
      regexp: "date.timezone ="
      line: "date.timezone = UTC"